app/assets/javascripts/listen_live.js.coffee, app/views/listen/index.html.erb, vendor/assets/javascripts/xml2json.js
Query Triton on-demand API for Listen Live preroll and visual ad.
I haven't checked this against the PFS player, but I believe the upcoming drive is done before this goes live.
=> Implement Triton on-demand ad for Listen Live page

app/controllers/api/public/v3/base_controller.rb, app/views/api/public/v3/episodes/_episode.json.jbuilder
This would be good to have since there's an endpoint to fetch an episode by its numerical ID but no way to find the ID through the API. This isn't blocking me on anything, so no rush or obligation.
=> Add episode ID to response object

app/controllers/api/public/v2/episodes_controller.rb, app/controllers/api/public/v3/episodes_controller.rb, app/models/external_episode.rb, app/models/external_program.rb, app/models/kpcc_program.rb, app/models/program.rb, app/models/show_episode.rb, app/presenters/program_presenter.rb, app/views/api/public/v2/events/_event.json.jbuilder, app/views/api/public/v2/schedule_occurrences/_schedule_occurrence.json.jbuilder, app/views/api/public/v3/events/_event.json.jbuilder, app/views/api/public/v3/schedule_occurrences/_schedule_occurrence.json.jbuilder, spec/controllers/api/public/v2/programs_controller_spec.rb, spec/controllers/api/public/v3/programs_controller_spec.rb, spec/models/external_episode_spec.rb, spec/models/external_program_spec.rb, spec/models/kpcc_program_spec.rb, spec/models/program_spec.rb
This has to come after #264. 
Speed up how we load programs, partially by removing the `.to_program` concept.
=> Speed Up Programs Endpoint; Remove `.to_program` from Programs

app/controllers/api/public/v3/schedule_occurrences_controller.rb, app/views/api/public/v3/schedule_occurrences/index.json.jbuilder, spec/controllers/api/public/v3/schedule_occurrences_controller_spec.rb
Just include ```pledge_status=true``` as a query parameter.
=> Make the pledge status in api/public/v3/schedule_occurrences optional.

Gemfile, Gemfile.lock, app/controllers/outpost/news_stories_controller.rb, spec/controllers/outpost/news_stories_controller_spec.rb
My previous solution wasn't displaying updated news story content because, for some reason, Rails wasn't parsing nested attributes from the JSON form data.  I'd have preferred that solution but I couldn't get it to work without having to do something kind of janky on the SCPRv4 side.
So instead I have reverted to using the version of Outpost before my previous change and am now transforming the keys of the news story attributes from the parameters.  I've previewed dozens of news stories in staging and they all seem to work and reflect changes that have not yet been saved.
If anyone has any suggestions on how to better accomplish this, please let me know.  I made a bunch of different attempts that ended up having different side-effects.
=> Fix the outpost preview to reflect unsaved changes

app/assets/javascripts/audio.js.coffee
Even though I can't immediately confirm this with my GA account(Real-time is not reflecting all of the events that I'm sending it), I have a hunch that most of the 'complete' events were not showing up because GA expects an integer as the event value and not a float; the event was still sending a value, which I had initially set to the current time of the audio.  If we look at the 'complete' events that do show up in GA, they all have non-float values(which is likely to happen occasionally).
Instead, I have changed it to just send a value of 1.  I'd like to merge this and wait and see if these events start coming in.
=> Remove float value that was being sent with audio complete event.

app/concerns/concern/sanitizers/url_sanitizer.rb, app/models/breaking_news_alert.rb, app/models/event.rb, app/models/related_link.rb, spec/concerns/concern/sanitizers/url_sanitizer_spec.rb, spec/models/breaking_news_alert_spec.rb, spec/models/event_spec.rb, spec/models/related_link_spec.rb
Addresses issue #279.  Adds a method that can be called by a 'before' callback which will strip preceding and trailing whitespaces in specified URL attributes.
=> Add sanitization concern to clean up trailing whitespaces in model URL attributes.

app/concerns/concern/associations/tags_association.rb
There was an issue with news stories trying to update tags with its published_at timestamp before it had a chance to assign its published_at.  This fixes that by checking for the published_at existence before trying to update the tags and then let the tags get updated on after_save when the published_at has now been added.
=> Prevent news stories from crashing on save when being published and having tags added

spec/controllers/programs_controller_spec.rb
Addresses issue #275.
I added testing for redirects in actions that use them.
The only one that I neglected to add a redirect test for was the #featured_show action, which does not have any testing for it at all.  I did not test it because I was not sure if it would be a waste of time(since, hypothetically, the old episode layout may get phased out).  Shall I leave it alone or test that as well?
=> Test redirects in the programs controller spec.

app/importers/npr_article_importer.rb
#240
This extends upon my original change, except the importer will now download more than 20 articles by downloading multiple batches of 20(which is a limit of the NPR API).  I have confirmed that it downloads more than 20 unique articles at a time.
=> Make NPR article importer adapt to failures and download more than 20 articles at a time.

app/models/audio.rb, spec/models/audio_spec.rb
#248
Adds a validation so that the enco_number can only be numeric, so this rejects word characters and whitespace.
=> Enco id validation

app/models/breaking_news_alert.rb, app/models/edition.rb, spec/models/breaking_news_alert_spec.rb
#357
To make it easier for Jason to parse through scpr.org generated emails in Eloqua, I have changed the naming conventions for those emails.
The short list, for example, was originally:
```[scpr-edition] Lorem ipsum dolor sit amet...```
And is now:
```[tsl 20151027] Lorem ipsum dolor sit amet...```
The abbreviation for the Monday Short List is ```tslm```
The name for a Breaking News alert was changed from "scpr-alert" to simply "alert".
=> Eloqua naming conventions

app/views/programs/kpcc/_segment.html.erb, app/views/programs/kpcc/_segment_preview.html.erb, app/views/programs/kpcc/episode.html.erb, app/views/shared/new/_single.html.erb, app/views/shared/new/_single_blog.html.erb
#365 #358
Audio links that did not include context & via params now do.  Will add more if any are found.
=> Provide context in audio links that don't currently have it

app/controllers/listen_controller.rb, app/views/listen/pledge_free_error.html.erb, app/views/listen/pledge_free_off_air.html.erb, config/initializers/pledge_drive.rb, config/routes.rb
#361
*It won't let me reopen the other pull request because I force pushed.*
The pledge free stream now redirects to a flatpage with a message and a link to the regular live stream.
Instead of using Flatpages, I changed the error page and off air page to be their own templates.
The only thing that's different than what is represented in the image below are the share icons, which don't share up with this implementation.
EDIT: Oh, and I linked the FAQ page reference to spcr.org/pledge-free.
=> Redirect members from KPCC Plus to off air page

app/importers/pmp_article_importer.rb, app/models/content_byline.rb, app/models/news_story.rb, db/migrate/20151029212124_add_publisher_field_to_remote_article.rb, db/schema.rb, spec/factories/remote_articles.rb, spec/fixtures/api/pmp/ahp_stories.json, spec/fixtures/api/pmp/ahp_story.json, spec/importers/pmp_article_importer_spec.rb
#354
This is accomplished by explicitly naming the articles as they come in, since there isn't a fool-proof way to get the name from the API.  The audio from AHP uses a different schema so it has to be handled differently.
=> PMP Importer should attribute the correct organization name to AHP articles and add their audio

app/views/editions/email/_abstract.html.erb, app/views/editions/email/_banner.html.erb, app/views/editions/email/monday/template.html.erb, app/views/editions/email/template.html.erb
#378
An ad banner is now placed after the 4th(at most) story in both version of the Short List.
=> Short List Ad Placement

app/models/remote_article.rb, db/migrate/20151116220729_index_all_remote_articles.rb, db/schema.rb
#377
Added the ability to search RemoteArticles in Outpost.  This was basically just including the correct concern in the model.  Also wrote a migration to index existing remote articles.
=> Remote article search in Outpost

public/static/ckeditor/config.js
#389 
Configured the WYSIWYG in Outpost to include a dropdown for formatting with heading tags.
=> Add format selector to ckeditor.

app/jobs/job/retry_emails.rb, app/models/eloqua_email.rb, db/migrate/20151125223240_add_attempts_made_to_eloqua_emails.rb, db/schema.rb, lib/eloqua/entity.rb, lib/tasks/scheduler.rake, spec/models/eloqua_email_spec.rb
#384
Per the discussion between @sdillingham and myself, I've left the changes to the way we send emails on hold and have implemented a job that retries emails that have failed.  I think that creating a unified email queue is a good approach but this alone better addresses the heart of the ticket.  If this ends up being successful, then we can later consider merging in the work that changes the way that the emails get sent.
To sum it up, we are sending emails as we normally have been but now we have a job that looks for eloqua_emails that have been attempted at least once but still have not been marked as sent.
=> Retry failed eloqua emails

app/assets/javascripts/listen_live.js.coffee
Issue #396 
Intended to add support in the live stream code for both DAAST and VAST responses for preroll.
Note that lines 117 - 119 are incorrect and that will be fixed soon.
=> Add DAAST support to live stream

app/models/breaking_news_alert.rb, spec/models/breaking_news_alert_spec.rb
Addresses #402.  Only uses the "increment" badge string if the alert is not of the "audio" type.
=> Alert badge

app/concerns/concern/associations/pmp_content_association.rb, app/helpers/application_helper.rb, spec/concerns/concern/associations/pmp_content_association_spec.rb
Stories were failing to be published because an issue with the underlying implementation of #rendered_body was failing.  Not exactly sure how that came to be, since I basically re-wrote all that code yesterday.  But now I've written a test for it and it should be ready for another try.
=> Fix #rendered_body method for PMP Content Association

app/controllers/application_controller.rb, app/controllers/cache_controller.rb, app/jobs/job/most_commented.rb, app/jobs/job/most_viewed.rb, app/jobs/job/most_viewed_blog_entries.rb, app/models/cache.rb, app/views/home/index.html.erb, app/views/shared/masthead/_news.html.erb, app/views/shared/new/_single_blog.html.erb, app/views/shared/widgets/_most_popular.html.erb, app/views/verticals/business.html.erb, db/migrate/20160205232526_create_caches.rb, db/schema.rb, spec/models/cache_spec.rb
#407
I wrote a model that wraps around the Rails cache store that caches data in MySQL for items that are usually stored out-of-band.  This is so that, if a cache server goes down, we don't end up rendering all these items on every request.  If a cache server comes back online and there is an item that has been cached in MySQL, it will also write that data back to the cache server.
=> Cache data in MySQL in case Memcached goes down

app/controllers/listen_controller.rb, app/controllers/outpost/pledge_drives_controller.rb, app/controllers/outpost/podcasts_controller.rb, app/helpers/application_helper.rb, app/models/pledge_drive.rb, app/views/outpost/pledge_drives/_form_fields.html.erb, config/initializers/inflections.rb, config/initializers/pledge_drive.rb, config/routes.rb, db/migrate/20160201231927_create_pledge_drives.rb, db/migrate/20160202002651_create_pledge_drives_permission.rb, db/schema.rb, spec/factories/pledge_drives.rb, spec/models/pledge_drive_spec.rb
#376
Not sure if it's overkill, but I decided to try handling pledges using a table.  That way nobody has to commit and deploy code just to start a pledge drive, and they can be scheduled ahead of time.  Since it's an Outpost model, permission can be restricted to only certain people.  Pledge drives can also be enabled and disabled, overriding whether or not the current date falls within their time range.  I'd be happy to scrap this if all we really wanted was a second config parameter.
=> Add model to handle pledge drive date ranges.

app/concerns/concern/controller/show_episodes.rb, app/models/episode.rb, app/models/show_episode.rb, app/models/show_rundown.rb, app/models/show_segment.rb, app/views/api/public/v2/episodes/_episode.json.jbuilder, app/views/api/public/v3/episodes/_episode.json.jbuilder, app/views/layouts/homepage.html.erb, app/views/outpost/show_episodes/_form_fields.html.erb, app/views/programs/kpcc/_featured_story.html.erb, app/views/programs/kpcc/_segment.html.erb, app/views/programs/kpcc/episode.html.erb, db/migrate/20160218003730_make_show_rundowns_polymorphic.rb, db/schema.rb, spec/controllers/programs_controller_spec.rb, spec/models/show_episode_spec.rb, spec/models/show_rundown_spec.rb
#432 
Episodes can now be related to any Content Base model through rundowns.  So now, instead of simply having segments, an episode can have many segments, stories, shells, blogs, episodes, abstracts, events, pij_queries.  All of the content can be accessed at once using the `#content` method on the episode.
=> Allow episode rundowns to include any content base content

app/concerns/concern/associations/episode_rundown_association.rb, app/models/abstract.rb, app/models/blog.rb, app/models/blog_entry.rb, app/models/content_shell.rb, app/models/event.rb, app/models/news_story.rb, app/models/pij_query.rb, app/models/show_episode.rb, app/models/show_segment.rb, app/views/layouts/homepage.html.erb, app/views/programs/kpcc/_segment.html.erb, spec/concerns/concern/associations/episode_rundown_association_spec.rb
What I've done here is extracted the episode rundown relation code into a concern and included a before_save callback that will touch the parent episodes if the content has changed.  Theoretically, this should make it so that lists of episode rundown content in views can be fragment cached based on the episode object so that we do not always have to retrieve the individual pieces of content(which can come from multiple tables).
=> Make rundown content touch its parent episodes when it is updated

app/models/pmp/pmp_content.rb
Here's the scoop on why I'm choosing to do this.
Stories and related assets publish to the PMP just fine.  What happens is, if a story is updated or changed, say a piece of audio is switched, there's an ActiveRecord callback specified to destroy the old content from the PMP before publishing the new stuff.  The problem is occurring when, on delete, we need to grab the existing document from the PMP and then call #delete on it, which is a method provided by the PMP gem.  Somehow the document that we are getting back from the PMP isn't the expected one and it raises an error because it's trying to perform a delete API request for something without a GUID.  i.e., we are getting back the wrong thing from the API.
However, it's yet another problem that seems to not occur when I do it myself …
=> Rescue error from pmp and log it to NewRelic.

db/migrate/20160229171922_fix_orphaned_immigration_articles.rb, db/schema.rb
#435
This looks for article content with a category_id of 16(which is the ID of the immigration Category, which we deleted earlier), makes sure that each content is associated with the newer immigration Tag, and set the category_ids to `nil`.
See the issue for why this is the only deleted category I'm taking care of here. (i.e. Immigration is the only category with this problem).
=> Nullify category_id fields for content referencing the now-gone Immigration category

app/views/pmp/story.html.erb, db/migrate/20160302011026_force_republish_of_pmp_content.rb, db/schema.rb
Because we were using the render_asset method as normal, stories set to display a slideshow also include the slideshow and script tags in the rendered body.  This is a case where there should just be a photo.
=> Only render a photo for the PMP lead asset

app/importers/pmp_article_importer.rb, spec/importers/pmp_article_importer_spec.rb
PMP Article Importer now imports CA Counts stories from partners.
=> Pmp import ca counts

app/importers/pmp_article_importer.rb
Some CA Counts stories may not have any alternate links included with their PMP document.  The importer shouldn't fail when this happens since not all stories we will be receiving will have been published yet.
=> PMP Importer shouldn't fail if no "alternate" array is provided

db/migrate/20160322172046_clear_duplicate_external_episodes.rb, db/schema.rb
This migration cleans out any external episodes that are duplicates based on title and program id.  
In reference to #468.
=> Add migration to clear existing external episode duplicates.

app/concerns/concern/associations/pmp_content_association.rb, spec/concerns/concern/associations/pmp_content_association_spec.rb
#450 
When someone checks the 'publish to pmp' checkbox in Outpost, that change is not reflected in a Secretary::Version.  This is because it isn't a real ActiveRecord attribute but set as an instance variable and is reflected from the existence of a related pmp_content record.  The problem is we can't `tracks_association` on the pmp_content because it's being created/destroyed with a callback and not a setter method.
I decided to make this change here because, while it would be nice to make Secretary support arbitrary methods(i.e. virtual attributes), it currently relies a lot on the way that ActiveRecord handles showing changes and I don't think it's a good idea to meddle with what ActiveRecord is doing.  At least this minor change is kept where all the PMP association behavior is …
=> Have changes to publish_to_pmp boolean reflect in versions

app/importers/rss_program_importer.rb
#468
This should prevent the duplication we've been seeing, since it appears that episodes are occasionally modified and the GUIDs for what is conceptually the same episode are different between duplicates, as well as summary content.  The only consistent key seems to be the title of the episode so, instead of looking at the GUID(which is oddly unreliable), this checks if an episode exists for a program using the title.
=> Check if episode exists based on title and program id.

app/views/programs/kpcc/_segment_preview.html.erb
Videos weren't displaying in the segment preview in outpost.  The video does display on the live site, however.  It's because the preview template passes an article to #render_asset rather than a ShowSegment like on the live site.  Not sure why this makes a difference, but just passing the ShowSegment solves this.  It should be possible to pass articles to #render_asset and have them always work the same when the contentbase changes are merged in, but for now this will make the preview work properly.
=> Make video lead assets work in segment preview

Gemfile, Gemfile.lock
#482 
This updates the gemfile to point to v3 of the NPR gem, which resolves the bug introduced by a change in behavior with the NPR API that prevents importing some shows.
=> Update NPR gem version to 3.0.0.

app/assets/javascripts/outpost/autosave.js.coffee, app/views/outpost/resource/edit.html.erb, app/views/outpost/shared/sections/_autosave.html.erb
We had to roll back the last release because the keyup/down events we were tracking were conflicting with key combos.  Instead, we're now shimming DOM objects so that we can directly track changes on all of them, including things like the textareas that are being dynamically modified so their change/input events aren't triggered.
=> Outpost Autosave Release 2

app/assets/javascripts/application.js
Use of moment functions were failing in production because, for some reason, Browserify require functions are not working properly after minification(works just fine in development).  The fix was to change it to use Sprockets require directives, and I'm not sure why I couldn't do it this way previously.
=> Change moment-strftime and moment-twitter to use Sprockets directive.

app/assets/javascripts/outpost/autosave.js.coffee
This turns off the modal after form submit no matter what, which is a temporary workaround for a few issues causing the modal to bug people even after they have saved.
=> Remove autosaved doc on form submit because we are still somehow getting modals triggered after save.

app/assets/javascripts/outpost/application.js, app/views/outpost/shared/sections/_autosave.html.erb, public/static/ckeditor/config.js
This reverts the autosave feature in Outpost to the old CKEDITOR autosave plugin, as there have been continuing issues with the new version.
=> Revert to CKDEDITOR autosave plugin.

app/assets/javascripts/application.js, app/assets/javascripts/election-results.coffee, app/assets/javascripts/election-results.js, app/views/layouts/homepage.html.erb
#531
Grabs markup from one of our servers that returns election results for the upcoming primary, and displays it in the hero position on our homepage.  Starts displaying on June 7 at 8am and stops displaying June 8 at 11:59pm.
=> Display election results on Homepage

app/assets/javascripts/better_homepage/better_homepage.js.coffee, app/assets/javascripts/framework.js.coffee
#551 
This behavior can still be enforced optionally because now options for the frontend app can be side-loaded from localStorage like so:
`window.localStorage.setItem('framework-options', JSON.stringify({development: true}))`
☝️ That ugly snippet will enable the app to reset the statuses of the homepage stories for development purposes.
👇 And this one will clear side-loaded options.
`window.localStorage.removeItem('framework-options')`
=> Don't reset article statuses to 'new' on load

app/assets/javascripts/better_homepage/better_homepage.js.coffee, app/assets/javascripts/framework.js.coffee
This just adds an option to persistent model behavior that specifies only what attributes we want to load from local storage.
=> Allow persistent models in framework to only load specific attributes

app/assets/stylesheets/better_homepage/application.css.sass, app/views/better_homepage/index.html.erb, app/views/layouts/better_homepage/_check_it_out.html.erb
This implements some basic fragment caching on the new homepage, and fixes a problem where the 'new' status pips were displaying on the headlines in the related content.
=> Caching and a UI fix

app/views/better_homepage/index.html.erb, app/views/layouts/better_homepage/_header.html.erb
I removed a few things, one of which was gaining us a trivial performance boost but was probably preventing the homepage cache from expiring when content changes.  The other part I removed was the periodic cache expiry; now it's supposed to only expire if content changes.
=> Remove some of the crust from the caching.

Gemfile, Gemfile.lock, app/controllers/better_homepage_controller.rb, app/helpers/application_helper.rb, app/helpers/better_homepage_helper.rb, app/views/better_homepage/_contents.html.erb, app/views/better_homepage/media/_block.html.erb, app/views/better_homepage/media/_large.html.erb, app/views/better_homepage/media/_medium.html.erb, app/views/better_homepage/media/_none.html.erb, app/views/better_homepage/media/shared/_extra.html.erb
- Prevents related content that has already been shown or is on the homepage as a story.
- Adds an autoprefixer that I've confirmed corrects some image display problems on Android browser and mobile Chrome.
=> Related Content Adjustments

app/assets/javascripts/better_homepage/application.js, app/assets/javascripts/better_homepage/better_homepage.js.coffee, app/assets/javascripts/better_homepage/lib/article-component.js.coffee, app/assets/javascripts/better_homepage/smarter-time.js.coffee
It turned out that moment.js, inside SmartTime, was being interfered with by the plugins it was using.  This was preventing any modification I made to locale strings from having any effect.  I ended up "forking" the SmartTime code and placing it in the BetterHomepage javascripts directory.  The changes were simply to remove those plugins, which we aren't actually using on the new homepage, and include an option to pass in custom locale/strftime strings.
As a result, the timestamps for stories are more "snappy".
=> Make story timestamp snappier.

Gemfile, Gemfile.lock, app/views/outpost/better_homepages/_form_fields.html.erb
#549 
This prevents events from being returned in the results for the aggregator in the Outpost editor for the new homepage, but allows for them to still be searchable.
=> Don't show events in recent content for the new homepage outpost aggregator.

app/models/show_episode.rb
Looking at staging, I'm not really sure how much of a temporary improvement this will be, but it should be safe to deploy and that might provide a better indication.
=> #get_article should be called instead of #to_article so that we aren't generating an article when we already have one indexed.

app/helpers/application_helper.rb, app/models/homepage_content.rb, app/models/show_segment.rb
Related to: #588
This is essentially undoing a specific change that may have been causing some performance problems, and uses a more direct means to get related content.  Initially, the homepage was relying on Elasticsearch but, since we are pre-caching the homepage, now there are things left over from that which rely on articles.  I'd like to further divorce the new homepage from articles over time.
=> Beta Homepage: Get related content from content objects instead of articles

app/controllers/feeds_controller.rb, app/views/feeds/shared/_instant_article.html.erb, lib/content_base.rb, lib/instant_articles_helper.rb, spec/spec_helper.rb
This makes some adjustments to our instant article feeds in order to meet Facebook's criteria.  Only our own articles and blog entries should be included in the feed, and a minor syntactical issue caused by a p tag was removed.  I have also attempted to disable the "mystery error" tests, as the fact that they randomly fail tells us nothing and only serve to annoy the developer at this point.
=> Instant Article improvements

app/views/shared/content/default/_opengraph.html.erb, app/views/shared/new/_document_header.html.erb
#595
Prevents the default description from overriding the more specific one.
=> Allow default twitter description to be overridden.

app/views/shared/content/default/_opengraph.html.erb, app/views/shared/header/_document_header.html.erb, app/views/shared/new/_document_header.html.erb
#595 
Simply makes the implementation of opengraph and twitter tags a bit more consistent so that the correct tag displays every time.
=> Meta helper

app/concerns/concern/callbacks/expire_ingest_feed_cache_callback.rb, app/controllers/feeds_controller.rb, app/controllers/ingest_feed_controller.rb, app/models/blog_entry.rb, app/models/news_story.rb, app/views/feeds/apple.xml.builder, app/views/feeds/shared/_apple_article.html.erb, config/application.rb, config/routes.rb, spec/concerns/concern/callbacks/expire_ingest_feed_cache_callback_spec.rb
#581 
This moves the apple news and instant articles rss ingests to their own controller so that helper methods can be safely overridden.  Since I'm relying on MySQL queries to generate each feed, there is now caching of those queries and a callback added to NewsStories and BlogEntries that expires that cache upon changes to published content.  The apple feed has some improvements taken from their documentation, like adding meta tags that specify an image and an author.
=> Apple news improvements

app/importers/npr_article_importer.rb
#612 
I have a suspicion that the duplication was being caused by, at some point, the article_id being cast as a different type from the fetched article ID(string being evaluated against an integer).  It's not clear to me why this didn't seem to always happen, but the article_id, when queried from the database, comes back as a string.
So I did two things:
- Convert both the ID in the database and the fetched ID to strings during comparison.
- Fetch existing IDs from the database in bulk as opposed to calling an #exists? query on every article fetched.  This makes the importer much faster.
On staging, we were seeing up to 3 duplicates per story.  After implementing this change, no duplicates come in no matter how many times I run the importer, so I think this is worth deploying to …
=> Prevent NPR remote articles from being pulled in multiple times

app/importers/npr_article_importer.rb, app/models/remote_article.rb, db/migrate/20160816202513_make_remote_articles_unique.rb, db/schema.rb, spec/controllers/outpost/remote_articles_controller_spec.rb
#613 
This is to prevent Remote articles from the NPR importer from creating duplicate records, which may be happening due to competing processes.
=> Enforce uniqueness of remote articles at the database level.

lib/instant_articles_helper.rb
Sometimes we have embeds where the author referenced it in a paragraph above.  Yet, if we remove these links, it leaves the reader with nothing and it's confusing.  That may have been the reason behind Facebook's last cryptic complaint about our articles.  So I'm going to merge this, wipe our existing articles out, and try again for acceptance.
=> Allow embed placeholder links to persist

app/views/feeds/shared/instant_articles/_default.html.erb, lib/instant_articles_helper.rb
A few changes were made to how we are translating our articles into Instant Articles, so as to better comply with Facebook's format and prevent relatively harmless warnings from cluttering up the article management interface(warnings should be for more serious issues if they occur).  In part because only recent articles are accepted, I am deploying this to production so that new stories can regularly be added and previewed.
=> Instant articles updates

app/concerns/concern/controller/amp.rb, app/controllers/blogs_controller.rb, app/controllers/news_controller.rb, app/controllers/programs_controller.rb, app/views/amp/audio.html.erb, app/views/amp/default.html.erb, app/views/layouts/application.amp.erb
#616
- Prevent NewRelic from inserting JavaScript on AMP page requests.
- Correct AMP page titles.
NOTE: The problem with NewRelic earlier this week was caused by an unescaped character in the newrelic.yml file in Consul.
=> Google AMP Changes

app/concerns/concern/controller/amp.rb, app/helpers/application_helper.rb
Our helpful friend Eloqua adds parameters that conflict with the parameter we were using to tell SCPRv4 to load the AMP version of a new story, causing some links in the Short List to go to the AMP version of the page instead of the normal version.  Clearly, this is undesired, especially if the story is being loaded on desktop.
This commit changes the AMP implementation to work from the file type instead of a query parameter, which shouldn't conflict with anything.
=> AMP route fix

config/routes.rb
#652 
Stories got lost as a result of a database failure, so this creates some redirects from their old URLs to their new ones.
=> Create some temporary redirects for stories

Gemfile, Gemfile.lock, app/models/breaking_news_alert.rb, config/initializers/one_signal.rb, config/templates/secrets.yml.ci, spec/jobs/job/send_mobile_notification_spec.rb, spec/models/breaking_news_alert_spec.rb
#645 
Breaking news alerts now get pushed both to OneSignal and Parse.
=> Push breaking news alerts to OneSignal

app/assets/javascripts/better_homepage/application.js, package.json
#666 :metal:
This polyfill takes care of both the logo in IE11 as well as the other icons that required `use` tags.
=> Switch to a different SVG polyfill

app/views/layouts/application.amp.erb
#676
This adds Comscore tracking to AMP pages using the amp-analytics plugin, as described [here](https://www.ampproject.org/docs/reference/components/amp-analytics#comscore).
=> Add comscore tracking to amp analytics.

app/models/tag.rb, app/views/better_homepage/_tag_cluster.html.erb
#695 
- Tag save triggers homepage cache reload if on that homepage.
- Removes "learn more" from tag clusters.
- Adds bullets back to abstracts on homepage.
=> Tag cluster improvements

app/views/feeds/shared/_instant_article.html.erb, app/views/feeds/shared/instant_articles/_tracking_scripts.html.erb
#675 
Adds simple GA pageview tracking to Facebook Instant Articles.  Will work on adding other metrics later, but first we need to verify that this even works at all and what it returns us.
=> Add basic GA tracking to Instant Articles.

app/views/feeds/shared/instant_articles/_tracking_scripts.html.erb
#699 
This adds scroll tracking to Instant Articles analytics code.
=> Require scroll tracker plugin for facebook GA.

app/assets/stylesheets/events.css.scss, app/assets/stylesheets/new/_newsletter_appeals.css.scss, app/views/events/_events_list.html.erb, app/views/events/kpcc_in_person.html.erb, app/views/shared/widgets/_events_subscribe.html.erb
#719
Implements the AC in that last ticket by changing event signup copy, the copy when there are no events to display, and where the event newsletter signup element appears.
=> Update events listings for when there are no events.

app/assets/stylesheets/new/_newsletter_appeals.css.scss, app/views/programs/kpcc/_segment.html.erb, app/views/shared/new/_single.html.erb, app/views/shared/new/_single_blog.html.erb, app/views/shared/widgets/_donate.html.erb, app/views/shared/widgets/_short_list_subscribe.html.erb
#722 
Some CSS was added to make the CTA headline scale with the width of the page.  It would be a good idea to consider adding a convention to the style guide for accomplishing this with other headlines.  Preferably with vw units or calc(), which has an amazing amount of support now.
http://caniuse.com/#feat=calc
=> Implement in-article donate CTA

app/assets/stylesheets/better_homepage/application.css.sass, app/views/layouts/better_homepage/_header.html.erb
#726 
I adjusted the widths of the menu columns so they are more aligned on mobile, and had to create a bit of an override on the third column in Support Us in order to prevent it from floating underneath the first two columns.  This could be a good argument for why the dropdown content should be re-implemented without using the flex grid system from the style guide, but I'll be taking a closer look at this during the unification tickets and I may be able to just do away with the override without changing the dropdown columns.
I also am adjusting the size of the text of the support buttons in the masthead so that the text doesn't widow, therefore the buttons stay uniform.
=> Add links under Support Us in masthead

app/models/kpcc_program.rb, app/views/outpost/kpcc_programs/_form_fields.html.erb, app/views/shared/widgets/_program_newsletter_subscribe.html.erb, db/migrate/20170223223040_add_newsletter_signup_description_to_programs.rb, db/migrate/20170223224858_add_newsletter_form_title.rb, db/migrate/20170223225810_migrate_the_frame_form_text.rb, db/schema.rb
Adds fields to KPCC Programs in Outpost to allow for a custom heading and caption for a newsletter signup appeal.
If the heading is left blank, the default is: 
> Like {SHOWNAME}?
If the caption is left blank, the default is:
> Catch up with the {SHOWNAME} newsletter.
The default caption will correct itself if the show name starts with "The".
=> Make newsletter signup more flexible.

app/views/programs/external/show.html.erb
This fixes the issue with HTML entities appearing in external show titles on external program index pages.  They're not HTML, so the sanitization doesn't need to happen.
=> Relaxed_sanitize doesn't need to happen on show titles.

app/models/pij_query.rb
This makes PijQueries compatible with the homepage.  A few attributes needed to be aliased, as they don't completely match other ContentBase-type models.
=> Make PijQuery homepage-compatible.

app/views/shared/media/components/_meta.html.erb
- The icon lives in `public/static/images/icon_line-video.svg`
- Adding the "Video" string to the array concatenates to the path to the svg
=> Renders video meta tag to articles with video content

app/models/article.rb, app/views/amp/audio.html.erb
Adds context query parameter to audio URLs that get played on AMP pages.  Will return "news" for news stories, or the slug for anything that has a slug like segments.
=> Add context parameter to AMP audio.

app/views/listen/index.html.erb, app/views/outpost/external_programs/_form_fields.html.erb, app/views/outpost/podcasts/_form_fields.html.erb, app/views/podcasts/index.html.erb, app/views/programs/kpcc/_recent_episodes.html.erb, app/views/programs/kpcc/_recent_segments.html.erb
Public strings referring to iTunes will now read as "Apple Podcasts".
=> Convert references to iTunes to Apple Podcasts.

app/filters/filter/amp_filter.rb
Fixes this minor issue:
```
/scpr/scprv4_production/releases/20170425174000/app/filters/filter/amp_filter.rb:78: warning: character class has '-' without escape
```
=> Escape character that was raising warning in a regex matcher.

app/assets/stylesheets/amp/application.css.sass, app/concerns/concern/controller/amp.rb, app/filters/filter/amp_filter.rb
The spec for AMP images have changed from `data-width` and `data-height` to just requiring a `width` and `height` property.
Styles were added to `amp/application.css.sass`
=> Renders image tags in AMP pages, re-applies styling

app/assets/javascripts/event_tracking.js.coffee, app/assets/javascripts/exit-modal.js.coffee, app/controllers/programs_controller.rb, app/views/programs/kpcc/segment.html.erb
Now sends GA events for the following triggers:
- Open Modal
- Close Modal
- Subscribe (for Short List or Frame modals)
- Click (for Pledge Drive modals)
Each event includes a label with the following format:
`{Modal Type} | {URL} | {optional: Subscription}`
Example events:
Category: `Modal`
Action: `Open Modal`
Label: `Modal Type: The Frame Exit Modal | URL: http://localhost:3000/programs/the-frame/2017/02/18/55164/a-new-study-puts-some-numbers-to-hollywood-s-issue/`
Category: `Modal`
Action: `Subscribe`
Label: `Modal Type: The Frame Exit Modal | URL: http://localhost:3000/programs/the-frame/2017/02/18/55164/a-new-study-puts-some-numbers-to-hollywood-s-issue/ | Subscription: The Frame`
The result on Google Analytics looks like this:
=> GA Event Tracking for Exit Modals

app/models/breaking_news_alert.rb, spec/models/breaking_news_alert_spec.rb
Removes the Parse push notification code and handles OneSignal errors.
=> Remove old parse push notification code from breaking news alerts.

config/routes.rb
Add /listen-live and /listenlive as redirects to /listen_live, because they're nicer.
=> Live stream redirect

app/controllers/feeds_controller.rb, app/jobs/job/better_homepage_cache.rb, app/models/better_homepage.rb, app/views/feeds/flash_briefing.json.jbuilder, config/routes.rb
This will allow the flash briefing to be derived from homepage content.  For now, I will leave the category endpoints in place.
=> Add flash briefing endpoint for homepage content.

app/controllers/api/public/v3/members_controller.rb, app/controllers/api/public/v3/settings_controller.rb, app/models/member.rb, app/models/setting.rb, app/views/api/public/v3/members/_member.json.jbuilder, app/views/api/public/v3/members/show.json.jbuilder, app/views/api/public/v3/settings/index.json.jbuilder, config/routes.rb, db/migrate/20170522185650_create_members.rb, db/migrate/20170522202220_create_settings.rb, db/schema.rb
The concepts of **settings** and **members** have been added to SCPRv4.  The member table schema reflects that of what we currently store in Parse, although the column names are snake-case.  
Settings have a **key**, **value**, and **context**.  Context can be used to store settings for specific environments like iOS.  The default context is **global**.  The value is always JSON.
`/api/v3/settings` Returns global settings.  This will also include information about the current pledge drive if there is one.
`/api/v3/settings/:context` Returns a settings object for a specific context.
`/api/v3/members/:token` Returns a single member for the provided token.  Currently returns very limited information for an existing member, or a 404 response if a member is not found.
=> Add some new endpoints for settings and members.

app/views/shared/cwidgets/_comments.html.erb
Quick fix that re-enables Disqus comments for post pages
Would it have been better to use '//' instead of explicitly stating the protocol 'https://'?
Examples:
- Broken: https://www.scpr.org/programs/take-two/2016/02/05/46208/do-female-democrats-feel-torn-between-clinton-and/
- Fixed: https://scprv4-staging.scprdev.org/programs/take-two/2016/02/05/46208/do-female-democrats-feel-torn-between-clinton-and/
=> Change protocol for disqus script import

app/views/api/public/v3/programs/_program.json.jbuilder, app/views/outpost/external_programs/_form_fields.html.erb, app/views/outpost/kpcc_programs/_form_fields.html.erb, db/migrate/20170810193354_add_description_text_and_phone_number_to_programs.rb, db/schema.rb, docker-compose.yml, spec/controllers/api/public/v3/programs_controller_spec.rb
Adds `description_text` and `phone_number` to KPCC programs and external programs in the API and Outpost.
=> Add fields to programs api

app/views/outpost/external_programs/_form_fields.html.erb, app/views/outpost/kpcc_programs/_form_fields.html.erb
Just moves mobile-specific fields in program edit pages to their own section.
@nakedsushi
=> Move program mobile fields to their own section/heading.

app/assets/javascripts/visual_campaign.js.coffee
Staging URL: https://scprv4-staging.scprdev.org/
Current production url (Mixed Content Error): https://scpr.org
Changelog:
- Changed the protocol for the Visual Campaigns endpoint to `https://`
- The request is no longer blocked as a result
=> Change the protocol for the visual campaigns endpoint

app/assets/javascripts/new/single.js, app/views/shared/new/_document_header.html.erb
This snippet enables Google Tag Manager in article pages and retains scroll depth functionality.
It was previously disabled because our scroll depth script (which reports when a user's viewport reaches a subscription sign up) would no longer send events if GTM was enabled. However, there was a nice option I found called `gtmOverride` that when set to true will allow you to continue to send the custom scroll events regardless. Was tested for a couple of days last sprint and confirmed to work via @patrickdougall.
=> Enable article gtm

app/filters/filter/amp_filter.rb
This should fix the 500 error for the behest amp page. Some scripts are inline scripts (which would have no `src`), so rails would raise an error that `.match` wasn't a method. In this implementation, it would only try to match if there's an actual `src`
=> Only tries to regex if node['src'] is a string

app/views/shared/new/_document_header.html.erb
Adds KPCC's specific link ownership meta tag to the global header of the site. This should allow for the ability to overwrite link metadata (i.e. headline, description, image) in the Graph API or in Page composer.
The meta tag was taken from the settings of KPCC's facebook page.
=> Adds fb:pages meta tag site-wide for facebook's link ownership req

Gemfile, Gemfile.lock, app/assets/javascripts/outpost/asset_host/assethostbase.js.coffee.erb, app/assets/stylesheets/layouts/article.css.sass, app/cells/article/show.erb, app/cells/article_cell.rb, app/cells/asset_cell.rb, app/controllers/news_controller.rb, config/environments/development.rb, db/schema.rb
I've tried to address the problem with portrait-shaped assets and floating them within the article body.
What I've decided to do is abandon the idea of having paragraph nodes at the same level as the rest of the main elements, and instead wrapping the article body/paragraphs within one container to maintain their size.  I chose this because, without such a container, and due to using percentages to maintain sizes, floating items in the body becomes haphazard and unpredictably shifts underneath the right-hand column at some screen sizes no matter how much finesse I add to its positioning.
The downside is that it prevents us from interleaving sidebar items within the article body, but it's a fine tradeoff because we end up with essentially the same advertisement positioning we have in the …
=> Floating assets

app/assets/stylesheets/layouts/article.css.sass, app/cells/article_cell.rb
Removes unnecessary height property in articles bodies. Also overflows the parent body so that the floats work as expected.
=> Fixes embeds

app/cells/comments/show.erb
This reverts back to the way this disqus snippet was written before, except instead of calling `to_article`, we call `get_article` (which checks the ES first I believe). I initially took out `to_article` for performance reasons, but that proved to be a problem for any other model that wasn't a vanilla NewsStory.
=> Fixes missing comments

app/cells/article_cell.rb
I was incorrectly accessing this variable
=> Re-enables pij message at the bottom of articles

app/views/verticals/education.html.erb, app/views/verticals/environment.html.erb, app/views/verticals/health.html.erb, app/views/verticals/politics.html.erb
A simple fix to tighten up the way supporters in the verticals look like. I changed the pipes to be the same tag (`h2`) as the ones for the supporters.
Before:
After:
=> Fixes vertical supporters so that the pipes are the same height

app/cells/archive_tab/blogs.erb, app/cells/archive_tab/news.erb, app/cells/archive_tab/programs.erb, app/cells/archive_tab_cell.rb, app/cells/article/show.erb, app/cells/article_cell.rb, app/cells/biography/show.erb, app/cells/biography_cell.rb, app/cells/blog_entry_cell.rb, app/cells/featured_interactive/show.erb, app/cells/featured_interactive_cell.rb, app/cells/featured_story/category_view.erb, app/cells/featured_story/vertical.erb, app/cells/featured_story_cell.rb, app/cells/latest_news/categories.erb, app/cells/latest_news/featured.erb, app/cells/latest_news_cell.rb, app/cells/topic_cluster/vertical.erb, app/cells/topic_cluster_cell.rb
Sorry for all the file changes! Had to add the method to every cell that needed it.
The new method first checks if there is an `original_object` from the input object, and uses that first. Otherwise, it uses the input object directly. This handles both cases where the data might not be in the right shape (might not be an article). Inside the code block, it checks whether that bio `is_public`, and if it is, creates a link, or else it just displays the `display_name`
Example: https://scprv4-staging.scprdev.org/news/2017/11/03/77364/amber-alert-chevy-truck-fort-tejon-gomes/
=> Enables listing and linking as it was in pre-AU

app/assets/stylesheets/application.css.sass, app/cells/breaking_news_alert/show.erb, app/views/layouts/application.html.erb
The properties in the cell's template weren't being included. By adding `model.try()` to all of the necessary properties, there shouldn't be anymore access errors. Another way to do this would be to put includes at the top of the cell's controller. For now though, I think this way should be sufficient.
This is on me for not ever testing this feature. Since there isn't a mock for this (as far as I know), I'm importing the old stylesheet.
=> Fixes breaking news access errors

app/cells/event/show.erb, app/cells/event/style.sass, app/cells/event_cell.rb
- Fixes it so that the end datetime is displayed if the event spans multiple days
- Also checks if its the same day, and if it is, renders in a more readable format (e.g. Monday, November 6, 1:00pm - 4:00pm)
- Applies same style rules as article pages
=> Fix event date

app/cells/listen_live/show.erb, app/views/listen/index.html.erb
- A `<title>` tag from an svg was changing what was being reported to chartbeat
- Will eventually move these svgs out of here and into `scprsprite.svg`
=> Fix listen live reporting

app/cells/recent_content_cell.rb
Fixes this bug: 
- Includes the class inside the cache_key to make sure these cells don't display without their necessary classnames
=> Fixes cache key to be more specific for recent content

app/cells/comments/show.erb
This fixes the comment section in cases where there are single quotes within a headline.
calling .to_json already wraps the string inside quotes, so we can take out the single quotes that are wrapped outside of the variable.
Examples below:
Before (wrapping with ''):
‘“The audacity of ‘woke’”’;
After (taking out ''):
“The audacity of ‘woke’”;
=> Fixes comment section by unwrapping to_json'd strings

app/cells/article_cell.rb
Assigns an arbitrary string (in this case an incrementing version number) to create a new cache key.
Currently in "Can't automatically merge". I'll resolve the conflicts before trying to push
=> Bump cache key

app/cells/article_cell.rb
Sometimes the current model doesn't have a `joined_bylines` property. In that case, check if there's an `original_object` property and use the `joined_bylines` from there instead.
=> Fixes contributing bylines by checking if theres an original_object

app/cells/event/show.erb, app/cells/event/style.sass, app/cells/event_cell.rb, app/cells/upcoming_events_list_cell.rb, app/controllers/events_controller.rb, app/views/events/show.html.erb, config/routes.rb, spec/controllers/events_controller_spec.rb
Changes the events listed in the KPCC In Person Landing Page from upcoming to `upcoming_and_current`. Also doesn't display the KPCC In Person prologue header for sponsored events.
=> Fixes event listings

app/cells/article_cell.rb, app/cells/asset/default/slideshow.html.erb, app/cells/asset_cell.rb, app/views/shared/new/_single_preview.html.erb
Changelog:
- Adds cases to access the `asset_display` properties, `hidden` and `slideshow`, for if the model is either a NewsStory of Article (this is because for preview to work, the @entry is actually a NewsStory, and calling get_article will revert to a cached version of the article)
- Ensures that slideshows do not take from `inline_assets`
- bumps the cache_key
=> Fix slideshows

app/views/pij_queries/show.html.erb
This adds meta tags to PIN pages. Prior to this, it would default to the generic meta tag which includes the page title.
This is an example of a page fed to facebook debugger:
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fscprv4-staging.scprdev.org%2Fnetwork%2Fquestions%2Fselena
=> Adds meta tags and correct page title for PIN pages

app/assets/stylesheets/scpr-style-guide-v4/objects/_figure.css.sass, app/cells/article_cell.rb, app/cells/asset_cell.rb, app/cells/featured_story/program.erb
- Imposes an aspect ratio for the featured image at the top of an article
- Goes to the default aspect ratio (100% width) for inline assets
- Fixes the featured image in the Program page to be 1.5:1 (dubbed the `"classic"` aspect)
=> Fix aspects

app/cells/episode/show.erb, app/cells/more_from_episode_cell.rb, app/views/programs/kpcc/_segment_preview.html.erb, app/views/shared/content/default/_opengraph.html.erb
- Only shows "More from episode" cell if there is an actual episode attached to the segment
- Shows the header for the segment list in the episode page only if there are any segments
- Fixes outpost previews for show_segments by giving it the original object (Outpost object)
- Defaults to general meta image for articles with no assets
=> Fixes program related bugs, outpost, and meta images

app/assets/stylesheets/layouts/article.css.sass, app/assets/stylesheets/layouts/flatpage.css.sass
This change overflows the flatpage body so that it doesn't try to follow it's parents flow (which has float right for the sidebar). It also adds proper margins underneath the sidebar for when the sidebar is taller than the body.
=> Fix flatpage overflow

Gemfile, Gemfile.lock
This updates `yajl-ruby` and `rubyzip`. `pygments.rb` relied on `yajl-ruby` v. 1.2.0, so I had to update that to the nearest version that didn't require that version anymore.
=> Updates vulnerable gems

app/cells/article/meta_tags.erb, app/cells/article_cell.rb, app/views/news/story.html.erb, app/views/programs/kpcc/segment.html.erb
Rather than use the method `render_content` to render the meta tags, I figured it would make sense to include that template as a method to the article cell. We can then use cell caching to cache the tags. 
Prior to this, `render_content` would check if there was a cache for a particular story, and if not, call `to_article` again on the input model to get it ready for the opengraph template. Since the model is usually in the correct shape by the time it reaches the article_cell, we wouldn't need to re-call `to_article` in the new implementation.
Also, rather than using `h()` to escape html tags, I elected to use `.to_json` like in the comment cell. Doing so meant removing the quotes that wrapped around the variables (ie `content=<%= strip_tags(model.teaser).to_json %>` instead of …
=> Add meta_tag template to article cell

app/controllers/programs_controller.rb, app/views/programs/standard_program.erb, config/routes.rb, spec/controllers/programs_controller_spec.rb
This kind of page is currently broken in prod: http://www.scpr.org/programs/airtalk/featured?page=1568&view=segments
It's because the #featured_show method was rerouted to the normal #show method. This change re-enables this functionality and hopefully fixes old links that appear in search results (which currently redirect to the program page).
=> Reroute old links

app/assets/stylesheets/layouts/flatpage.css.sass, app/cells/flatpage/show.erb, app/cells/flatpage_cell.rb, app/views/flatpages/show.html.erb, app/views/people/index.html.erb, app/views/press_releases/index.html.erb, app/views/press_releases/show.html.erb
- Applies a full width flatpage structure to press release individual/index pages
- Fixes the way flatpage titles are sized
- Fixes float issues with staff directory page (which is also based on flatpage styling/structure)
=> Press release templates

Gemfile, Gemfile.lock, config/initializers/memory_logger.rb
The changes add Oink, a memory logger, to the environment logger.
Running `bundle exec oink log/production.log` should give a rundown of the worst culprits when it comes to memory usage / active record calls.
=> Add memory logger

app/assets/javascripts/aplicayshun.js, app/assets/javascripts/audio.js.coffee, app/cells/article/show.erb, app/views/layouts/application.html.erb, app/views/shared/footer/_tracking_scripts.html.erb
Major changes:
- Removed the GA script from the footer and added exact copy of it to GTM (labeled 'Legacy GA Script'). This script will run first in priority
- Removed the `event_tracking` script from application.js ('aplicayshun.js') and added the transpiled JS to GTM (labeled 'Legacy Event Tracking Script'). This script will run after the GA script mentioned above.
- Fixed an issue with the way quartiles are being reported
Minor adjacent change:
- Removed unused behavior functionality from articles
=> Remove GA script and event_tracking script

app/assets/stylesheets/layouts/article.css.sass, app/cells/ad_cell.rb, app/views/programs/standard_program.erb
This change fixes styling for ordered lists (numbers weren't showing up). Also updates the cache_key for ad cells to be more specific, and fixes an error in external program pages where airdate and host names were not showing up.
=> Fix ordered lists

app/cells/featured_quote/show.erb, app/cells/featured_story/vertical.erb, app/cells/related_links_cell.rb, app/cells/resources/show.erb, app/cells/topic_cluster/vertical.erb, app/concerns/concern/associations/related_content_association.rb, app/models/quote.rb, app/models/tag.rb, app/models/vertical.rb, app/views/better_homepage/_tag_cluster.html.erb, app/views/blogs/entry.html.erb, app/views/news/story.html.erb, app/views/outpost/verticals/_form_fields.html.erb, app/views/programs/kpcc/_segment_preview.html.erb, app/views/programs/kpcc/segment.html.erb, app/views/shared/new/_single_preview.html.erb, spec/concerns/concern/associations/quote_association_spec.rb, spec/concerns/concern/associations/related_content_association_spec.rb, spec/features/vertical_spec.rb, spec/models/quote_spec.rb, spec/models/vertical_spec.rb
These changes are in response to memory bloat issues that have been occurring recently. After some investigation, I recognized that active record transactions were really long. For verticals, it would average +20 seconds. The newest changes in this branch bring that down to around 80ms without caching.
There's another branch that has further optimizations site-wide that improves performance of news stories and segments down to 10ms range per request (https://github.com/SCPR/SCPRv4/tree/reduce-activerecord-usage), but it diverged so much (66 file changes) that I thought I would start over and create a branch with the most important changes first, then slowly add the rest of the optimizations later.
The general idea is that `to_article` is a bit too expensive, and being called too often in …
=> Aesthetic Unity: Speed revision 01

app/assets/javascripts/better_homepage/better_homepage.js.coffee, app/cells/footer/show.erb, app/cells/masthead/show.erb, app/cells/masthead_cell.rb, app/views/layouts/amp/_footer.html.erb, app/views/layouts/application.html.erb, app/views/layouts/better_homepage/_footer.html.erb, app/views/layouts/better_homepage/_header.html.erb, app/views/layouts/minimal.html.erb, app/views/listen/index.html.erb, app/views/outpost/shared/footer/preview/_document_footer.html.erb, app/views/shared/footer/_document_footer.html.erb, app/views/shared/new/_document_footer.html.erb, app/views/shared/new/masthead/_main_nav.html.erb
Some GA attributes were missing for donation clicks in the masthead and footer. This PR adds them back with new specifications (per @patrickdougall).
The events used to look like this:
`Category: Menu`
`Action: Donate`
`Label: Donate`
Patrick wants the new events to look like the following:
`Category: Menu`
`Action: Donate`
`Label: {url path}`
Other changes:
- Removes event tracking instantiation from the homepage and outpost (since this is being done GTM side now)
- Removes caching on the masthead (so that the request.path isn't also cached, also performance isn't dramatically affected when removed).
- Fixes Listen Live event tracking by including the GTM snippet properly via `<%= render "shared/new/meta_header" %>`
=> Fix donation tracking

app/assets/stylesheets/scpr-style-guide-v4/objects/_figure.css.sass, app/cells/asset/default/slideshow.html.erb
The changes presented here fix the way portraits show up in slideshows, and also center contains the image and adds a grey background to portraits in the hero asset.
Also fixes a bug where inline assets would show up in the thumbnail lists
=> Fixes slideshow sizing (plus numbering issue)

app/models/external_program.rb, app/models/kpcc_program.rb
#585
Does what it says on the tin using Rails' `dependent: destroy` option.
Did the same thing for both KPCC programs and external programs.
=> Make programs destroy their child records upon destruction.

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/outpost/base_controller.rb, config/initializers/new_relic.rb, config/newrelic.yml
Updated Newrelic agent to the latest version and renamed deprecated methods to their new counterparts.  It appears to be reporting fine in staging.
=> Update newrelic agent to 4.x

app/cells/article_cell.rb, app/cells/asset/default/photo.erb, app/cells/asset_cell.rb
There was a bug where all inline images would be a video if the first asset (the lead asset) happens to be a video. The changes below make it so that if an asset cell is created, it only applies a `videoid` and `assethost` class variable for that individual asset.
=> Bug: Checks asset type on an individual basis

app/assets/stylesheets/layouts/event.css.sass, app/assets/stylesheets/scpr-style-guide-v4/objects/_figure.css.sass, app/cells/event_cell.rb, app/cells/highlighted_events_cell.rb, app/cells/upcoming_events_cell.rb, app/cells/upcoming_events_list_cell.rb
Changes in this PR:
- Styling options for hero assets match article template styling
- Fix the asset_display check so that it returns nil if hidden
- Applies that logic to lists so that when it shows up in a list and its hidden, it also returns nil
=> Fixes event asset display

app/models/schedule_occurrence.rb
Changes the Schedule Occurrence record from a `recurring` occurrence to a `distinct` occurrence if any of these properties are changed:
- `starts_at`
- `ends_at`
- `program_id`
- `(event_title & info_url)`
Before, only `starts_at` and `ends_at` were properties that transitioned an occurrence to `distinct`.
Distinct occurrences have a higher priority over recurring occurrences and are not overwritten during the daily job, `BuildRecurringSchedule` (which deletes all future occurrences and replaces them).
Way to test:
1. Go to a recurring occurrence in outpost (e.g. https://scprv4-staging.scprdev.org/outpost/schedule_occurrences/867375/edit)
2. Change the program and save
3. The record should now be a `distinct` occurrence.
4. Run the job `rake scprv4:schedule:build` in `scprv4_staging`
5. …
=> Adds more conditions to register transition from Recurring to Distinct

app/cells/article/meta_tags.erb, app/views/layouts/application.html.erb
This change creates a meta tag that contains a story's tags. Useful for analytics. Also removes an unnecessary `<title>` tag.
=> Adds story tags to meta header

app/cells/article_cell.rb, config/initializers/assethost.rb
Changes in this PR:
- Protocol is initialized in AssetHostClient initializer to ensure all requests to AH has the right protocol. This is taken from the Rails configuration variable for `assethost.protocol`.
After doing the above change and pushing to staging, I noticed that there were some assets that were still not switching to `https`. I found out that there are some assets that are cached indefinitely (no expiration date). @Ravenstine had fixed it in this commit: https://github.com/SCPR/asset_host_client/commit/d869cb63647fb7d6c9e3e42832394051eb3cc634#diff-ff89ed48a670a3ebd756b89a999da3a3, so this is no longer a problem for assets posted after this commit. However, there are probably a few assets prior to this commit that still live in the cache. When I manually cleared the …
=> Fix asset protocol

config/environments/production.rb, config/environments/staging.rb
From the `dalli_store` docs, you can set a global expiration: https://github.com/petergoldstein/dalli#configuration
> **expires_in:** Global default for key TTL. Default is 0, which means no expiry.
This will take care of pages with mixed content errors, e.g. https://www.scpr.org/education, because those were stored in the cache before the 1 minute expiration write logic was put into effect.
This is in conjunction with another PR that adds expirations to cache reads: https://github.com/SCPR/asset_host_client/pull/2
Note: Pages with ads will continue to have mixed content errors because ads are served with the `http` protocol for some reason. Will create another ticket to address this in the future.
=> Sets the global expiration for the cache to one week

app/controllers/sitemaps_controller.rb, app/views/sitemaps/news.xml.builder
Addresses #408
Adds new tags to existing news and blog entry sitemaps.
=> Add google news sitemap tags to news and blog sitemaps.

app/assets/javascripts/README.md, app/assets/javascripts/audio.js.coffee, app/assets/javascripts/listen_live.js.coffee, app/cells/listen_live/show.erb
Changes proposed:
- `addToDataLayer` method is used to push to the dataLayer so that GTM scripts can access it
- adds `play`, `pause`, and `change` events to the dataLayer
- `change` event occurs when the current audio source being loaded is different from its immediate predecessor
- added comments/explanation for changes
To test:
- Go to GTM and turn on "Preview" mode
- Visit this page: https://scprv4-staging.scprdev.org/programs/take-two/2017/12/01/60481/cruising-through-the-2017-la-auto-show/
- Choose the dataLayer tab
- Click the play button
- A dataLayer object with `eventAction: play` should show up
- Minimize the GTM dev tool (because it's blocking the audio bar)
- Press pause, and then click the second audio element (or click the second audio element and then click pause)
- …
=> Adds GTM Data Layer logic to Audio Player Events

Gemfile, Gemfile.lock, app/cells/upcoming_events_list/README.md, app/cells/upcoming_events_list/show.erb, app/cells/upcoming_events_list_cell.rb, spec/cells/upcoming_events_list_spec.rb, spec/controllers/sitemaps_controller_spec.rb, spec/fixtures/api/assethost/asset.json
Takes the new `image_gravity` property from AssetHost and adds it as a `background-position` value to images cropped into squares on this page: https://scpr.org/events/kpcc-in-person. 
**Documentation:** https://github.com/SCPR/SCPRv4/blob/9127f96ae3ccdf604cfb2540431b7eace3563a49/app/cells/upcoming_events_list/README.md
**Tests:** https://github.com/SCPR/SCPRv4/blob/9127f96ae3ccdf604cfb2540431b7eace3563a49/spec/cells/upcoming_events_list_spec.rb
**New dependencies added to Gemfile:**
- `rspec-cells`
**Misc:**
- Added to the sitemap test to indicate which templates should be expected for each sitemap
=> Adds `image_gravity` to `upcoming_event_list_cell`

app/cells/appeal/README.md, app/cells/appeal/podcast.erb, app/cells/appeal_cell.rb, app/presenters/program_presenter.rb, spec/cells/appeal_cell.rb
The previous implementation of presenting podcast links in external pages was partially hardcoded. The changes here now get the proper links, `podcast` and `rss`, and shows them in the cell if they are available. If neither are available, the cell will not render. Assumptions are tested in the cell spec linked below.
**Documentation:** https://github.com/SCPR/SCPRv4/blob/bbe1ee345e830fe4564440aebbe67110c3f88129/app/cells/appeal/README.md
**Tests:** https://github.com/SCPR/SCPRv4/blob/bbe1ee345e830fe4564440aebbe67110c3f88129/spec/cells/appeal_cell.rb
**Staging demo:**
(XML) https://scprv4-staging.scprdev.org/programs/1a
(Neither) https://scprv4-staging.scprdev.org/programs/reveal/
=> Fixes podcast link bug for external program pages

app/models/schedule_occurrence.rb
There's an issue where filtering by date in the schedule occurrence page on outpost gives you dates in GMT. So if you chose "2018-02-01" for example, you would get results from "2018-01-31" and "2018-02-01".
The MySQL database uses the system's time zone, so the original query `select * from schedule_occurrences where DATE(starts_at) = ?` would always return results for that day in GMT.
I thought of possibly changing the global time zone in MySQL, but doing so would only apply to records written afterward. Also, `starts_at` and `ends_at` are stored as `datetimes` which don't include timezone information, so there wouldn't be an easy way of ensuring a datetime is in the correct zone after the change.
I eventually landed on getting the system time zone and comparing it with the Rails app …
=> Schedule Occurrence's filter function adjusts according to system tz

app/cells/popular_articles_cell.rb, app/models/show_episode.rb, app/views/shared/media/_media.html.erb, db/migrate/20180227011442_add_short_headline_to_show_episodes.rb, db/schema.rb
Resolves #1132
In the rare instance that an episode referred to a homepage article, the homepage cache would try to render the episode as related content as if it were an article.  The problem is that not only do episodes not behave like articles, but it has a #content method that does a different thing than what is expected by the related links cell.
This should no longer be a problem now that episodes return a short_headline and the template no longer changes behavior depending on the presence of a #content method, but if there is a HomepageContent type.
=> Show episodes

app/models/list.rb, app/views/outpost/lists/_form_fields.html.erb
List types are changed to match API endpoints that are useful to the iOS app.  So instead of the Rails model names, they're "article", "program", and "episode".
=> List type changes

app/cells/episode/README.md, app/cells/episode/show.erb, app/cells/episode_cell.rb, app/views/programs/episode.erb, spec/cells/episode_cell.rb
It used to be possible to include non-`ShowSegment` records in `ShowEpisode` pages. However, since AU, only `ShowSegments` have been showing up because it only pulls `ShowSegment` records in the cell (with `model.try(:to_episode).try(:segments)`. In this PR, we go back to using the `@content` instance variable that was supposed to be used to render this list, and make the cell more passive.
**Documentation:** https://github.com/SCPR/SCPRv4/blob/236b2c83bd071b742df37feb7932b21fe2c9a146/app/cells/episode/README.md
**Test:** https://github.com/SCPR/SCPRv4/blob/236b2c83bd071b742df37feb7932b21fe2c9a146/spec/cells/episode_cell.rb
**Staging demo:**
(Heterogeneous) https://scprv4-staging.scprdev.org/programs/take-two/2018/02/23/17893/
(Homogeneous) …
=> Allow for a heterogenous list in ShowEpisode pages

app/models/audio.rb, app/views/podcasts/podcast.xml.builder
This change adds a `<megaphone:externalId>` tag to the xml so that we have an easy way to retrieve the episode from Megaphone's API.
=> Adds an 'obj_key' tag for Megaphone's API

app/importers/npr_article_importer.rb, app/importers/pmp_article_importer.rb, spec/fixtures/api/npr/stories-altered.json, spec/fixtures/api/pmp/marketplace_stories_altered.json, spec/importers/npr_article_importer_spec.rb, spec/importers/pmp_article_importer_spec.rb
#492 Remote articles from NPR and PMP now will pull in updated headlines, teasers, and URLs.
=> Allow remote articles to pull in the latest headlines.

app/cells/latest_news/categories.erb, app/cells/latest_news/style.sass
The latest news page will no longer have the image features, and I made the reverse-chron content to be full-width.
https://github.com/SCPR/digital_products/issues/559
=> remove featured category images from latest news page

Gemfile, Gemfile.lock, app/controllers/outpost/show_episodes_controller.rb, app/models/show_episode.rb, app/views/outpost/shared/sections/_podcast_ad_placements.html.erb, app/views/outpost/show_episodes/_form_fields.html.erb, app/views/podcasts/podcast.xml.builder, config/initializers/megaphone.rb, spec/features/outpost/manage_show_episodes_spec.rb, spec/fixtures/api/megaphone/episode.json, spec/models/content_base/show_episode_spec.rb, spec/spec_helper.rb, spec/support/shared_examples/shared_resource_request_specs.rb
**The main file to look at is: `app/models/show_episode.rb`.**
I added getters and setters for the following megaphone properties:
- `preCount`
- `postCount`
- `insertionPoints`
On save, if any of the above are changed, it executes a `put` request.
**Other features include:**
- Appends the `Rails.env` to the podcast rss output so that changes in local/staging don't affect production records.
- Only showing the "Podcast Ad Placement" widget on shows that are "onair"
- If the initial `get` is unsuccessful, it disables the widget and shows a notice that the podcast record is unavailable for editing.
- Form validation for the insertion point gives immediate feedback
**Testing**
- `spec/features/outpost/manage_show_episodes_spec.rb`
- `spec/models/content_base/show_episode_spec.rb`
=> Integrate Megaphone into Outpost

app/models/list.rb, app/views/api/public/v3/articles/_article.json.jbuilder, app/views/outpost/lists/_form_fields.html.erb
Major changes:
- Can add a `ContentShell` to a list of articles in outpost
- Exposes a `type` property in the article object
For example, a content shell will return an object with `type: content_shell`.
The idea is that the app can use this information to decide how to render the contents, i.e. a "Go to link" button if the object is a `ContentShell`
=> Adds ContentShells to allowed content types for "article" selection

app/importers/pmp_article_importer.rb
Changes:
- rescues any error that occurs during a PMP API call
The error that keeps happening is a 504, which is usually a timeout error. I was able to perform the queries manually through rails console, and they are giving back valid responses, so for now we'll rescue by defaulting the `stories` variable to an empty array.
=> Rescues errors that occur when pulling in from PMP

app/importers/npr_article_importer.rb
Changes:
- Looks for a `DataPoint` called "npr_auto_publish_on", and if it's set to 0, it turns off autopublishing, set to 1, it turns it back on.
- Moved the rails environment check to the `auto_publish` method because thats where other blocking conditions happen (such as `elligible_for_autopublish?`).
=> Adds a check for an on/off switch and uses that if it exists

app/controllers/api/public/v3/members_controller.rb, app/controllers/listen_controller.rb, app/models/member.rb
There's a bug where if a user is in the Parse DB, but uses the iOS app, they won't have access to KPCC+ because the iOS app looks for their token in the Member table only. This is the fix:
1. If a member comes in thru the web's listen live for KPCC+, we check the parse DB as usual, and if their token is correct, copy that record to the Member table.
1. If a member comes in thru the new iOS api call, check the Member table as usual but *also* if they don't exist in the member table, check Parse and if they exist, copy that record over.
=> Looks for members in Parse and then populates Members if found

app/helpers/homepage_helper.rb, app/views/better_homepage/_latest_from_laist.html.erb, app/views/better_homepage/_latest_headlines.html.erb, app/views/better_homepage/_right_asides.html.erb
Major changes:
- There is a section at the right rail of the homepage that lists the latest 5 LAist entries
- "Latest NPR headlines" are moved down to position B
- Ad position A is moved outside of the "Latest NPR headlines" block
Note:
- There isn't any deduping logic, so editors have to be mindful of what is in the middle rail/ side rail
=> Update homepage to include latest 5 LAist entries

app/helpers/homepage_helper.rb, app/views/better_homepage/_latest_from_laist.html.erb
In conjunction with this Movable Type PR: https://github.com/SCPR/movabletype-laist/pull/16
The changes proposed here will perform a GET request to the RSS feed instead of the API. This is so that the resulting feed doesn't include any `@sponsor` entries, but another nice side effect is that it will most likely be unaffected by the incomplete object bug that occasionally happens with the movabletype data api.
=> Changes the GET request to GET from the RSS feed instead of the API

app/importers/rss_program_importer.rb
Found in this doc: https://docs.ruby-lang.org/en/2.0.0/OpenURI/OpenRead.html
> :read_timeout option specifies a timeout of read for http connections.
Adds a read timeout to escape if an rss feed isn't returning at a reasonable time period
=> Adds a read timeout to the open-uri call
