Gemfile, Gemfile.lock, app/models/show_episode.rb
Bryan fixed SCPR/secretary-rails#14, so update versions and add back the `tracks_association :rundowns` in ShowEpisode.
=> Update secretary-rails and add tracks_association back to ShowEpisode

app/controllers/outpost/show_episodes_controller.rb, app/views/programs/kpcc/episode.html.erb
Since we're already kicking @episodes, I figured I'd go ahead with the idea I had initially so I could move ahead with other things.  Let me know what direction we want to go in with this.
=> Archive picker caching fix

app/controllers/api/public/v3/schedule_occurrences_controller.rb, app/views/api/public/v3/schedule_occurrences/index.json.jbuilder, spec/controllers/api/public/v3/schedule_occurrences_controller_spec.rb
=> Add boolean to schedule_occurrences response to indicate if a pledge

app/models/content_base.rb
=> Use floats and round up in ContentBase pagination math.

Gemfile, Gemfile.lock
=> Update which embeditor-rails version to pull from.

public/static/ckeditor/plugins/embed-placeholder/plugin.js
Addresses #256
Should be merged when Embeditor-rails has been updated.
=> Add Document Cloud option to ckeditor embed.

app/assets/javascripts/application.js, app/assets/javascripts/listen_live.js.coffee, vendor/assets/javascripts/jquery-ajax-xdomain.js
Switch Listen Live prerolls to ADTECH.
=> Switch Listen Live to ADTECH

app/concerns/concern/sanitizers/content.rb, app/concerns/concern/sanitizers/url.rb, app/models/blog_entry.rb, app/models/breaking_news_alert.rb, app/models/content_shell.rb, app/models/event.rb, app/models/news_story.rb, app/models/pij_query.rb, app/models/press_release.rb, app/models/related_link.rb, app/models/show_segment.rb, spec/concerns/concern/sanitizers/content_spec.rb, spec/concerns/concern/sanitizers/url_spec.rb
=> Add content sanitizer and make the sanitizer concerns more uniform.

app/views/layouts/homepage.html.erb
=> Cache broadcast bar based on entire current and next episode objects.

app/jobs/job/twitter_cache.rb
=> Let twitter cache job continue even if a handle is not found.

app/jobs/job/twitter_cache.rb, config/initializers/new_relic.rb
#236
Reports the NotFound error to NewRelic with the twitter handle.
=> Twitter handle

app/views/events/_event.html.erb, app/views/shared/widgets/_events_subscribe.html.erb
=> Events signup

app/assets/javascripts/utilities.js.coffee, app/views/shared/cwidgets/_social_tools.html.erb, app/views/shared/new/_social_share.html.erb
#366
I've removed the JavaScript and HTML relating to Facebook and Twitter social counts.
=> Remove social counts for Facebook and Twitter.

app/controllers/programs_controller.rb, app/views/programs/kpcc/_featured_programs.html.erb, app/views/programs/kpcc/_recent_segments.html.erb, config/newrelic.yml
(Creating PR to make a few comments)
=> Improve segment performance

app/assets/javascripts/listen_live.js.coffee
=> Revert "Integrate Nielsen SDK"

Gemfile, Gemfile.lock, app/jobs/job/archive_versions.rb, config/initializers/aws.rb, config/templates/secrets.yml.ci, lib/tasks/scheduler.rake, lib/tasks/scprv4.rake, lib/version_table_archiver.rb
#414 
This adds a task will create a zipped CSV file of old version records that are greater than a year old, upload the zip file to Amazon S3, and delete the old records from the table.
=> Archive and delete old Secretary::Versions

app/models/cache.rb, spec/models/cache_spec.rb
There were just a few alterations that needed to be made to both the cache model and the tests for it.  The key row also is now unique.
=> Cache model implementation fixes

app/views/outpost/homepages/_form_fields.html.erb
SCPR/design#62
Pretty straight-forward.
=> Let homepages display events.

Gemfile, Gemfile.lock, config/database.yml, config/environments/development.rb, config/initializers/aws.rb, lib/tasks/db.rake
This should fix the problem of database.yml not picking up the docker container IP for connecting to the development database.  DBsync gem is also cleaned out.
=> Change how docker machine variables are initialized

app/concerns/concern/associations/pmp_content_association.rb, app/models/pmp/pmp_story.rb
=> Strip certain tags from templated body

app/views/pmp/_footer.html.erb, app/views/pmp/story.html.erb
=> Make pmp story template more fault-tolerant and wrap lead asset in article tag

app/views/shared/header/_document_header.html.erb, app/views/shared/header/_mogo_pixel.html.erb, app/views/shared/new/_document_header.html.erb
:point_up:
#473 
It's my understanding that having another GTM script should be just fine so long as it's using a different data layer.
=> Swap old Mogo pixel for GTM tracking script.

app/views/shared/header/_document_header.html.erb, app/views/shared/new/_document_header.html.erb
=> Add noindex meta tag to staging to prevent Google from crawling it

app/assets/javascripts/outpost/autosave.js.coffee, app/views/outpost/shared/sections/_autosave.html.erb
This addresses the problems we found during our QA.
=> Outpost autosave npm

app/assets/javascripts/application.js, app/assets/javascripts/smart_time.js.coffee, package.json
A compatible version of moment needed to be explicitly required.
=> Extend and require strftime modules

app/assets/javascripts/application.js, app/assets/javascripts/election-results.js, app/views/layouts/homepage.html.erb
We don't need this anymore, so out it goes!
=> Remove election results

app/assets/javascripts/better_homepage/better_homepage.js.coffee, app/assets/javascripts/framework.js.coffee, app/assets/stylesheets/better_homepage/application.css.sass, app/views/better_homepage/_contents.html.erb, app/views/better_homepage/index.html.erb, app/views/better_homepage/media/shared/_headline.html.erb, app/views/better_homepage/media/shared/_headline_large.html.erb, app/views/better_homepage/media/shared/_headline_top.html.erb, app/views/better_homepage/whats-next-component.hbs
- No longer hides from ads or large images.
- Passes behind large images on scroll.
- Though not mentioned before, there's CSS3 fading, which has been there for a little while.
=> Whats next refinement pass #1

app/assets/javascripts/better_homepage/better_homepage.js.coffee, app/assets/javascripts/framework.js.coffee, app/assets/javascripts/outpost/homepage/application.js.coffee, app/views/better_homepage/media/shared/_call_to_action.html.erb, app/views/better_homepage/media/shared/_related.html.erb, app/views/layouts/better_homepage/_header.html.erb
#546 
Additional tracking implemented:
- Scroll depth
- Article clickthroughs w/ scroll depth
- Related Content clickthroughs
- Donate button click
- Check It Out clickthroughs
- Call to Action clicks
=> Add GA Tracking to Beta Homepage

app/assets/javascripts/better_homepage/better_homepage.js.coffee, app/assets/javascripts/better_homepage/lib/article-component.js.coffee, app/assets/javascripts/better_homepage/lib/article.js.coffee, app/assets/javascripts/better_homepage/lib/boundary.js.coffee, app/assets/javascripts/better_homepage/lib/whats-next-component.js.coffee, app/views/better_homepage/_contents.html.erb, package.json
- Fixes whats next for Safari.
- Allows scoping boundaries to specific components.
=> Safari fixes

app/assets/stylesheets/better_homepage/application.css.sass, app/views/better_homepage/media/shared/_call_to_action.html.erb, app/views/better_homepage/media/shared/_cta_link.html.erb, app/views/better_homepage/media/shared/_extra.html.erb
#571 
Fixes CTA links and gives related content precedence over CTA.
=> Call to Action Improvements

app/assets/stylesheets/application.css.scss, app/assets/stylesheets/beta-opt-in.css.sass, app/views/layouts/homepage.html.erb
#582
There was an opt-in button a while ago, but this one is stylized.
=> Add opt-in button to the classic homepage

app/models/content_shell.rb, app/views/outpost/content_shells/_form_fields.html.erb
#599 
Content shells now support related content.
=> Add related content relation to content shells.

app/concerns/concern/callbacks/apple_news_callback.rb, app/jobs/job/publish_apple_news_content.rb, lib/apple_news.rb
A block ad component is inserted at the 3rd component index or greater index if the component before it is a figure(e.g. image).
=> Fix async publish and insert ad component

app/views/verticals/health.html.erb
#638
Self explanatory.  See markup change.
=> Update sponsorship information on the health vertical.

app/assets/javascripts/better_homepage/application.js, app/assets/javascripts/better_homepage/better_homepage.js.coffee, app/assets/javascripts/better_homepage/html-collection-foreach-polyfill.js, app/assets/javascripts/better_homepage/page-adjuster.js.coffee, app/assets/stylesheets/better_homepage/application.css.sass, app/views/better_homepage/index.html.erb, app/views/layouts/better_homepage.html.erb, package.json
Fixes:
- Branding, though other SVG icons are still unable to load.
- Content width problem when scaling down on IE.
- White space at bottom of page on non-webkit browsers.
=> IE Improvements Round #1

Gemfile, Gemfile.lock, config/honeybadger.yml
@Ravenstine Can you take a look at this? Let's pair tomorrow morning so you can show me how to deploy to staging and then production.
https://github.com/SCPR/SCPRv4/issues/665
=> Adds Honeybadger gem to report errors

app/models/breaking_news_alert.rb
#668
Fixes OneSignal pushes and does not interfere with current Parse push logic.
=> Fix OneSignal push.

app/assets/stylesheets/better_homepage/application.css.sass, app/views/better_homepage/index.html.erb, app/views/layouts/better_homepage/_header.html.erb, package.json
#667
Includes some changes for the latest version of the style guide, mostly to improve the masthead.
=> Homepage refinements

app/assets/javascripts/application.js, app/assets/javascripts/better_homepage/application.js, app/assets/javascripts/better_homepage/page-adjuster.js.coffee, app/assets/javascripts/election-results.js.coffee, app/jobs/job/better_homepage_cache.rb, app/views/better_homepage/_contents.html.erb, app/views/better_homepage/_right_asides.html.erb, app/views/better_homepage/index.html.erb, app/views/layouts/homepage.html.erb
Adds embedded election results to both homepages.  Results will appear on the 8th(today) at 7:55pm and will disappear on the 9th at 11:59pm.
=> Election results 2016

app/assets/javascripts/better_homepage/application.js, app/assets/javascripts/visual_campaign.js.coffee, app/views/better_homepage/index.html.erb, app/views/layouts/better_homepage.html.erb
=> Add pushdown banners to beta homepage

app/assets/stylesheets/better_homepage/application.css.sass, app/controllers/better_homepage_controller.rb, app/views/better_homepage/_broadcast_box.html.erb, app/views/better_homepage/_feedback.html.erb, config/routes.rb
=> Goodbye classic homepage

config/application.rb, lib/actionpack/lib/action_controller/metal/url_for.rb
Our 2-year-old bug is finally coming to an end.  Test pass, and everything looks good on staging, so I'm going to make it live and we'll see what happens.
=> Add a monkeypatch for the Outpost routing bug.

.gitignore, Gemfile, Gemfile.lock, app/controllers/api/public/v3/lists_controller.rb, app/controllers/outpost/lists_controller.rb, app/models/list.rb, app/models/list_item.rb, app/views/api/public/v3/lists/index.json.jbuilder, app/views/outpost/lists/_form_fields.html.erb
This adds list item content to list index api endpoint.  Also exposes the `position` attribute for lists.
=> list improvements

app/controllers/api/public/v3/lists_controller.rb, app/controllers/outpost/lists_controller.rb, app/models/list.rb, app/views/api/public/v3/lists/index.json.jbuilder, app/views/api/public/v3/lists/show.json.jbuilder, app/views/outpost/lists/_form_fields.html.erb, db/migrate/20170414214509_change_timestamp_names_for_lists.rb, db/schema.rb, spec/models/list_spec.rb
=> Allow lists to support multiple contexts.

app/concerns/concern/controller/searchable.rb
This allows model search results to be sorted by timestamp in Outpost.
=> Fix failed ordering during search query in Outpost.

app/controllers/outpost/breaking_news_alerts_controller.rb, app/controllers/outpost/editions_controller.rb, app/models/breaking_news_alert.rb, app/models/edition.rb, app/views/outpost/breaking_news_alerts/_form_fields.html.erb, app/views/outpost/breaking_news_alerts/bodies.html.erb, app/views/outpost/editions/_form_fields.html.erb, app/views/outpost/editions/bodies.html.erb, app/views/outpost/shared/_submit_row.html.erb, config/routes.rb
Adds a button in Outpost for both Breaking News Alerts and Editions to generate HTML and Text bodies for emails.
=> Html bodies

Gemfile, Gemfile.lock
Updating the Gemfile since I updated the gem.
https://github.com/SCPR/SCPRv4/issues/927
=> Uses updated for https version of embeditor-rails

app/assets/javascripts/aplicayshun.js, app/assets/javascripts/slideshow/new_slideshow.js.coffee, app/assets/javascripts/slideshow/slideshow.js.coffee, app/assets/stylesheets/application.css.sass, app/assets/stylesheets/layouts/article.css.sass, app/assets/stylesheets/slideshow.css.scss, app/cells/article_cell.rb, app/cells/asset/default/photo.erb, app/cells/asset/default/slideshow.html.erb, app/cells/asset/default/video.html.erb, app/cells/asset_cell.rb, app/cells/category_cluster/show.erb, app/cells/content_cluster_cell.rb, app/views/layouts/application.html.erb
- Implements caching mechanisms for cells that exist in both the news story and program segment pages
=> News Story and Program Segment cell caching

app/assets/javascripts/aplicayshun.js, app/assets/stylesheets/layouts/article.css.sass, app/cells/asset/default/photo.erb, app/cells/asset_cell.rb, app/views/layouts/application.html.erb
https://github.com/SCPR/digital_products/issues/382
=> Fix CMS bookmarklet

Gemfile, Gemfile.lock, app/assets/javascripts/aplicayshun.js, app/assets/javascripts/outpost/asset_host/assethostbase.js.coffee.erb, app/assets/stylesheets/layouts/article.css.sass, app/cells/article/show.erb, app/cells/article_cell.rb, app/cells/asset/default/photo.erb, app/cells/asset_cell.rb, app/controllers/news_controller.rb, app/views/layouts/application.html.erb, config/environments/development.rb, db/schema.rb, public/static/ckeditor/plugins/inline-asset-placeholder/plugin.js, public/static/ckeditor/plugins/inline-asset-placeholder/src.js.coffee
This includes my work on the figure positioning and fixes related merge conflicts.
=> Figure positioning

app/cells/article_cell.rb
Not all asset placeholders may have a data-align attribute.
=> Figure positioning fix

app/cells/featured_programs_cell.rb, app/controllers/outpost/events_controller.rb, app/controllers/outpost/flatpages_controller.rb, app/controllers/outpost/pij_queries_controller.rb, app/controllers/outpost/show_segments_controller.rb, app/models/show_segment.rb, app/views/events/_event.html.erb, app/views/flatpages/_flatpage.html.erb, app/views/layouts/outpost/preview/new/application.html.erb, app/views/pij_queries/_pij_query.html.erb, app/views/programs/kpcc/_segment_preview.html.erb, app/views/shared/new/_single_preview.html.erb, spec/controllers/outpost/flatpages_controller_spec.rb
Outpost previews are copies of normal views (with a few cells removed for performance purposes).
Example: https://scprv4-staging.scprdev.org/outpost/news_stories/69215/edit
=> Update outpost previews

app/cells/appeal/breaking_news.erb, app/cells/appeal/editions.erb, app/cells/appeal/in_person_newsletter.erb, app/cells/appeal/newsletter.erb, app/cells/newsletter_appeal/show.erb
These updates were lost in the eloqua transition (due to focus being more on prod at the time).
=> Updates appeal forms to new SFMC forms

app/assets/stylesheets/application.css.sass, app/assets/stylesheets/kpcc-table.css.scss, app/assets/stylesheets/layouts/article.css.sass, app/assets/stylesheets/layouts/standard_program.css.sass, app/cells/article_cell.rb, app/cells/episode/style.sass, app/cells/episode_list/show.erb, app/cells/newsletter_appeal/style.sass, app/cells/popular_articles/side_bar.erb, app/cells/popular_articles_cell.rb, app/concerns/concern/controller/show_episodes.rb, app/controllers/programs_controller.rb, app/views/programs/external_program_episode.erb, app/views/programs/kpcc/segment.html.erb, app/views/programs/standard_program.erb, app/views/programs/standard_program_episode.erb, spec/features/programs_spec.rb
KPCC Program Episodes are now fed into the article template
=> Enables full functionality of Non-featured KPCC Programs

app/assets/stylesheets/layouts/article.css.sass, app/assets/stylesheets/layouts/flatpage.css.sass, app/cells/article/show.erb, app/cells/blog_hosts/show.erb
Fixes the floating popular now cell in blog entries, fixes missing host images, and fixes positioning in flatpages.
=> Fix blog float

app/cells/article/meta_tags.erb, app/cells/article_cell.rb
Properly includes ERB::Util for the html escape method
=> Fix metatag break

Gemfile, Gemfile.lock
Reverts gems back to the way they were prior to dependency update
=> Reverts Gemfile and Gemfile.lock

app/cells/ad_cell.rb, app/cells/article_audio/horizontal.erb, app/cells/article_audio/show.erb, app/cells/article_audio/style.sass, app/cells/article_audio_cell.rb
This change should render extra audio elements if there are any. When clicking on the play button, the audio bar should automatically update. Also fixes the cache_key for ad cells
=> Extra audio elements

app/controllers/programs_controller.rb, app/views/programs/kpcc/segment.html.erb
This change allows for the pledge drive modal to be edited via a flatpage.
=> Adds editing feature to pledge drive exit modals

spec/controllers/sitemaps_controller_spec.rb
Was broken after news sitemaps added.
=> Fix sitemaps controller tests.

app/controllers/outpost/lists_controller.rb, app/models/list.rb, app/views/api/public/v3/lists/index.json.jbuilder, app/views/api/public/v3/lists/show.json.jbuilder, app/views/outpost/lists/_form_fields.html.erb, db/migrate/20180222213348_add_type_field_to_list.rb, db/schema.rb
[#505](https://github.com/SCPR/digital_products/issues/505)
Adds types to lists for our lists endpoint.  It will return either an array of types, or it will return nothing.
=> List types

app/views/api/public/v3/lists/index.json.jbuilder, app/views/api/public/v3/lists/show.json.jbuilder
=> Pluralize types for lists.

Gemfile.lock, package-lock.json, package.json
Updates
- rack-protection
- ssri
=> Updates rack-protection gem and ssri node module

Gemfile, Gemfile.lock
I updated Embeditor to not use Embedly for YouTube.
=> Bump Embeditor version.

app/assets/stylesheets/layouts/program.css.sass, app/views/programs/show.html.erb
Changes:
- Replaces two column segment grid with single column episode list
- Updates layout styles to line it up properly across different viewport sizes
=> Replaces two column segment grid with single column episode list

app/controllers/listen_controller.rb
Removes parse logic and simply looks at whether there's a matching member
=> Removes parse logic from listen controller

app/models/audio_sync/program.rb
- Wraps the begin block (which has the directory read of a `media002` folder) with a 5 second timeout (new lines are 35 and 88).
=> Adds a 5 second timeout to the audio sync job
